apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: $CLUSTER_NAME
  region: $AWS_REGION

managedNodeGroups:
  - name: managed-ng-1
    instanceType: t3.large
    spot: true
    desiredCapacity: 2
    volumeSize: 30
    privateNetworking: true