apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      serviceAccountName: eks-edu-service-account-9641173
      containers:
      - name: my-app
        image: public.ecr.aws/nginx/nginx:1.27
