apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: $CLUSTER_NAME
  region: $AWS_REGION

addons:
- name: aws-ebs-csi-driver
  version: latest
  serviceAccountRoleARN: $ADDON_IAM_ROLE_ARN
  resolveConflicts: preserve